name: Build & Upload

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon

      # 🧩 Upload all .jar files from build or target directories
      - name: Upload all JARs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-jars
          path: |
            **/build/libs/*.jar
            **/target/*.jar
